 version: '3.4'
 
 services:
  starwarssupplywebapi:
    image: "andreraica/starwarssupplycalculator_webapi"
    build:
      context: ./StarWarsSupplyWebAPI
      dockerfile: Dockerfile
    ports:
      - '44351:44351'
 
  starwarssupplywebapp:
    image: "andreraica/starwarssupplycalculator_webapp"
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    environment:
      - API_URL=http://localhost:44351/swagger/v1/swagger.json
    depends_on:
      - 'starwarssupplywebapi'
  
# docker-compose up --build