version: '3.4'

# dockerfile: ./StarWarsSupplyWebAPI/Dockerfile
services:
  starwarssupplywebapi:
    image: "andreraica/starwarssupplycalculator_webapi"
    
# starwarssupplywebconsole:
  #   image: "starwarssupplycalculator_console"
  #   build:
  #     context: .
  #     dockerfile: \StarWarsSupplyConsole/Dockerfile

  
  
# docker-compose build ----- NOT WORKING
# docker-compose up