version: '3.4'

services:
  starwarssupplywebapi:
    image: "andreraica/starwarssupplycalculator_webapi"
    build:
      context: ./StarWarsSupplyWebAPI
      dockerfile: Dockerfile

  #starwarssupplywebconsole:
  #  image: "andreraica/starwarssupplycalculator_console"
  #  build:
  #    context: ./StarWarsSupplyConsole
  #    dockerfile: Dockerfile
  
# docker-compose build
# docker-compose up