# dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/core/sdk:3.1

COPY ./publish /publish
WORKDIR /publish

ENTRYPOINT ["dotnet", "StarWarsSupply.Presentation.Console.dll"]

# docker build -t andreraica/starwarssupplycalculator_console .

# >>> Publishing <<<
# docker login
# docker push andreraica/starwarssupplycalculator_console